# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palavras_Ignorar',
            new_name='Ignore_Words',
        ),
    ]
