# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_ingrediente',
            name='Ingrediente',
            field=models.CharField(max_length=500),
        ),
    ]
