# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20160826_1216'),
    ]

    operations = [
        migrations.RenameModel('Data_Way_Cooking', 'DataWayCooking'),
        migrations.RenameModel('Ignore_Words', 'IgnoredWords'),
        migrations.RenameModel('Ingredient_Spec', 'IngredientSpec'),
        migrations.RenameModel('Data_Ingredient', 'DataIngredient'),

        migrations.RenameField('DataWayCooking', 'Description', 'description'),
        migrations.RenameField('DataWayCooking', 'Recipe', 'recipe'),
        migrations.RenameField('DataWayCooking', 'Group', 'group'),
        migrations.RenameField('IgnoredWords', 'Word', 'word'),

        migrations.RenameField('IngredientSpec', 'Word', 'word'),
        migrations.RenameField('IngredientSpec', 'Count', 'count'),
        migrations.RenameField('IngredientSpec', 'Type', 'type'),

        migrations.RenameField('DataIngredient', 'Ingredient', 'ingredient'),
        migrations.RenameField('DataIngredient', 'Recipe', 'recipe'),
        migrations.RenameField('DataIngredient', 'Group', 'group'),

    ]
