# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20160828_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoredwords',
            name='word',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredientspec',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredientspec',
            name='word',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
