# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingredient',
            new_name='RecipeIngredient',
        ),
    ]
