# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='caloria_grama',
            new_name='caloria',
        ),
    ]
