# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_auto_20160707_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
