# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_auto_20160826_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('PT', 'Portuguese')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
